import os
import uuid
import matplotlib
matplotlib.use("Agg")

import matplotlib.pyplot as plt

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import FileResponse
from pydantic import BaseModel
from typing import List, Dict, Any

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    Image, Table, TableStyle
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet

from backend.api.dependencies import get_current_user
from backend.services.ai_service import ask_ai
from backend.models.report import Report
from backend.db.database import SessionLocal

# ✅ CLEAN ROUTER
router = APIRouter(
    prefix="/reports",
    tags=["Reports"]
)

# ---------------- REQUEST ---------------- #

class ReportRequest(BaseModel):
    job_id: int
    candidates: List[Dict[str, Any]]

# ---------------- HELPERS ---------------- #

def format_skills(skills):
    return ", ".join(skills) if skills else "N/A"

def safe_ai(prompt):
    try:
        return ask_ai([{"role": "user", "content": prompt}], [])
    except Exception:
        raise HTTPException(status_code=500, detail="AI report summary unavailable")

# ---------------- ROUTE ---------------- #

@router.post("/generate")
def generate_report(req: ReportRequest, current_user: str = Depends(get_current_user)):

    if not req.candidates:
        raise HTTPException(status_code=400, detail="No candidates provided")

    db = SessionLocal()

    candidates = req.candidates

    # -------- AI SUMMARY -------- #
    context = ""
    names = []
    scores = []

    for c in candidates:
        names.append(c.get("candidate_id"))
        scores.append(c.get("score"))
        context += f"{c.get('candidate_id')} score {c.get('score')} skills {format_skills(c.get('skills', []))}\n"

    prompt = f"""
Analyze these candidates:

{context}

Provide:
- Summary
- Top candidates
- Hiring recommendation
"""

    ai_result = safe_ai(prompt)

    # -------- FILE PATHS -------- #
    base_dir = os.path.abspath("reports")
    os.makedirs(base_dir, exist_ok=True)

    unique_id = uuid.uuid4().hex
    chart_path = os.path.join(base_dir, f"chart_{unique_id}.png")
    file_path = os.path.join(base_dir, f"report_{unique_id}.pdf")

    # -------- CHART -------- #
    plt.figure()
    plt.bar(names, scores)
    plt.title("Candidate Scores")
    plt.xlabel("Candidates")
    plt.ylabel("Score")
    plt.savefig(chart_path)
    plt.close()

    # -------- PDF -------- #
    doc = SimpleDocTemplate(file_path)
    styles = getSampleStyleSheet()
    content = []

    # LOGO
    try:
        logo = Image("backend/assets/logo.png", width=100, height=50)
        content.append(logo)
    except OSError:
        pass

    content.append(Spacer(1, 10))
    content.append(Paragraph("AI Recruitment Report", styles["Title"]))
    content.append(Spacer(1, 15))

    # SUMMARY
    content.append(Paragraph("Executive Summary", styles["Heading2"]))
    content.append(Spacer(1, 5))
    content.append(Paragraph(ai_result, styles["Normal"]))
    content.append(Spacer(1, 20))

    # CHART
    content.append(Paragraph("Candidate Score Analysis", styles["Heading2"]))
    content.append(Spacer(1, 10))
    content.append(Image(chart_path, width=400, height=250))
    content.append(Spacer(1, 20))

    # TABLE
    content.append(Paragraph("Candidate Evaluation", styles["Heading2"]))
    content.append(Spacer(1, 10))

    table_data = [["Candidate ID", "Score", "Skills"]]

    for c in candidates:
        table_data.append([
            c.get("candidate_id"),
            str(c.get("score")),
            format_skills(c.get("skills", []))
        ])

    table = Table(table_data)

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.grey),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
    ]))

    content.append(table)
    content.append(Spacer(1, 20))

    content.append(Paragraph(
        "Generated by WorkforceOS",
        styles["Italic"]
    ))

    doc.build(content)

    # -------- SAVE TO DB -------- #
    report = Report(
        job_id=req.job_id,
        file_path=file_path
    )

    try:
        db.add(report)
        db.commit()
    finally:
        db.close()

    return FileResponse(
        file_path,
        media_type="application/pdf",
        filename="AI_Hiring_Report.pdf"
    )
